### PR TITLE
UITableViewCellContentView styling for contentView of UITableViewCell

### PR DESCRIPTION
**Pull request by alexeyt820**

### CODE REVIEW

**Comment by alexeyt820** [comment]
Seems not necessary, can be done by other means

**Comment by alexeyt820** [comment]
Second thought, it still maybe useful if one one style all UITableViewCells without specifying custom nulClass

**Comment by Stunner** [comment]
If you could resolve the conflicts (brought about by merging in your other changes :P ), I'd be happy to review and merge this PR.

**Comment by alexeyt820** [comment]
Should be resolved

**Comment by timbodeit** [comment]
LGTM

**Pull request merged**
