### PR TITLE
More comprehensive unit tests 

### LINKED ISSUE #260: UILabel does not apply styling unless nuiClass is set
NUI doesn't apply styling to UILabel when using the default property name of `Label`. If I set `label.nuiClass = @"Label";` then it works fine.

### PR DESCRIPTION
**Pull request by timbodeit**
Built on top of #293.

* Rebased onto current master, resolved a couple merge conflicts.
* Fixed compatibility of the unit tests with various device/iOS version combinations.
* Fix #260 

Currently tests under iOS 7 are failing because reference images for `testButtonWithGradient` and `testSegmentedControlColorsRenderCorrectly` are missing.
@PabloLerma said he would help out with these tomorrow, as I currently can't get the iOS 7 Simulator to run on my machine. See discussion on #284.

### CODE REVIEW

**Comment by Stunner** [comment]
@PabloLerma The images you provided work with iOS 7.1, but not with 7.0.3. Can you please provide those images for 7.0.3? That should get the Travis CI check to pass and I will be able to merge.

**Comment by PabloLerma** [comment]
I don't have a 7.0.3 simulator :(
At this time we only support >= 8.0 so having a 7.1 was luck because I didn't delete XCode 6.4. I will ask my teammates anyway.

Sidenote: With 9.1 out there, supporting 7.0.3 is not too much? :P

**Comment by Stunner** [comment]
Thank you. I would like to forgo iOS 7 support as well. But since we are maintaining a library I feel that we should strive to support as many iOS versions within reason. If this was a standalone app that would be a different story but considering many apps utilize our code it is entirely possible that the popular apps that utilize our code still have thousands of iOS 7 users. I think it would be shameful if we couldn't support them, especially if we didn't have to go far out of our way to do so.

**Comment by timbodeit** [comment]
@PabloLerma @Stunner I'd drop this single unit test on <7.1 though.
Chances are, that if it works on iOS 7.1, 8.x and 9.x, it will work as expected on 7.0.

These snapshot tests are only a form of integration test anyways, that double checks the unit test for the respective renderer classes.

**Comment by Stunner** [comment]
@timbodeit Fair enough.

**Comment by PabloLerma** [comment]
:+1:

**Comment by PabloLerma** [comment]
Anyway for the record, it would be good if someone supporting <7.1 could provide us such images :smile:

**Comment by timbodeit** [comment]
Well theoretically, we could tweak the travis build script to send the images back to us, but that seemed to be too much work for a test that essentially just compares two screenshots.

**Pull request merged**
