### PR TITLE
Add a more comprehensive suite of tests.

### PR DESCRIPTION
**Pull request by squarefrog**
In light of [CocoaPod's Test Jam](http://blog.cocoapods.org/Test-Jammin/) I have taken the opportunity of merging all my previous tests and updating snapshots.

My previously submitted [issues](https://github.com/tombenner/nui/issues/created_by/squarefrog) still stand, and there are a couple of failing tests that should allow you to fix this and be confident that the fixes work.

This PR replaces #259.

### CODE REVIEW

**Comment by Stunner** [comment]
As this original fork seems to be very inactive, and considering I have a need to enhance this library I plan on actively maintaining this project on [my fork](https://github.com/Stunner/nui) for the foreseeable future. I have merged in your tests branch into a [tests branch on my fork](https://github.com/Stunner/nui/tree/tests), however 1 or 2 tests fail (depending on simulator version). If you could fix them so that they pass, or at the very least shed light on why they fail that would be appreciated. (I assume that when you wrote the tests you wrote them so that they all initially passed.)

**Comment by squarefrog** [comment]
It's been a few months since I looked at this. I believe the failing tests are to be correct: pointing out areas in which the library doesn't perform as intended.

To be honest, I originally submitted most of these tests over a year ago and they sat un-merged since. It doesn't seem like the maintainers particularly value testing, so I'm not going to waste any more time working on them.

If you want to carry on, then you have my blessing, but I'd rather dedicate my time to other projects that are more responsive.

**Comment by timbodeit** [comment]
Replaced by #313.
@squarefrog Thanks a lot for your awesome work!

**Comment by squarefrog** [comment]
:+1: pleasure!

**Pull request closed without merging**
