### PR TITLE
Remove Demo/Pods dir

### PR DESCRIPTION
**Pull request by timbodeit**
Personally I'm not a big fan of including copies of the full source of all the dependencies inside a frameworks repository.
In my opinion pull requests should be as small as possible, focus on the actual changes and not be cluttered by code changes from dependencies.

The `.travis.yml` already includes a `pod install` call and the Readme already advises the user to run `pod install` manually before trying out the Demo project.

Alongside this, I added a few other things to the `.gitignore` that I find reasonable and removed an xccheckout file.

### CODE REVIEW

**Comment by timbodeit** [comment]
@tombenner @Stunner Please have a look over this.

**Comment by tombenner** [comment]
LGTM, but it'd be good to get another pair of eyes on it, too :+1:

**Comment by Stunner** [comment]
Encountered this error when running `pod install`:

```
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Pre-downloading: `NUIParse` from `https://github.com/tombenner/NUIParse`
[!] Unable to satisfy the following requirements:

- `NUIParse (from `https://github.com/tombenner/NUIParse`)` required by `Podfile`
- `NUIParse (= 1.2)` required by `Podfile.lock`
```

Remove `Podfile.lock` from the repo as well and this pull request should be good to merge in.

**Comment by timbodeit** [comment]
I wouldn't remove the entire lockfile, as its a good reference what versions were actually used and causes the CI server to use the same ones.

The reason this was throwing an error is that the Podfile.lock was outdated. The Podfile was specifying to use the latest commit on master of tombenner/NUIParse. However the lockfile specified a specific version, that is older than the current one.

What I did instead was to remove the git url from the Podfile and update the Podfile.lock

**Comment by Stunner** [comment]
Interesting, I thought the Podfile.lock was always generated based on the contents of the Podfile. I thought it was a one way street. Didn't think the information of the Podfile.lock would matter much given that a pod install would overwrite it anyway.

**Comment by timbodeit** [comment]
`pod install` does not overwrite version numbers. That's what `pod update` is for.

`pod install` will install all dependencies from the Podfile in accordance with Podfile.lock, choosing older versions of Pods as required.
`pod update` will install the newest versions of all dependencies allowed by the Podfile ignoring the Podfile.lock.

That's the entire purpose of the lockfile. It gives you a way of making sure everybody is using the same versions without checking in all of the dependency code. Instead when you want to update the used version of a specific pod, commit those changes to the Podfile.lock

**Comment by Stunner** [comment]
Good to know. I had always been doing that via the `Podfile`. Thanks for sharing.

**Comment by timbodeit** [comment]
Well normally I use a combination of the two. The Podfile and more important the podspecs of any Pods could have a loose version requirement (e.g. by using the [~>](https://guides.cocoapods.org/syntax/podfile.html#pod) operator) and the Lockfile would help me get the exact version I was using in previous development when checking out an older commit.

**Pull request merged**
